#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
# Source0 file verified with key 0x865688D038F02FC8 (jdelvare@suse.de)
#
Name     : dmidecode
Version  : 3.2
Release  : 12
URL      : http://download.savannah.gnu.org/releases/dmidecode/dmidecode-3.2.tar.xz
Source0  : http://download.savannah.gnu.org/releases/dmidecode/dmidecode-3.2.tar.xz
Source99 : http://download.savannah.gnu.org/releases/dmidecode/dmidecode-3.2.tar.xz.sig
Summary  : No detailed summary available
Group    : Development/Tools
License  : GPL-2.0 GPL-2.0+
Requires: dmidecode-bin
Requires: dmidecode-license
Requires: dmidecode-man
Patch1: 0001-Use-modern-defaults.patch
Patch2: 0002-enable-debug.patch

%description
** INTRODUCTION **
Dmidecode reports information about your system's hardware as described in
your system BIOS according to the SMBIOS/DMI standard. This information
typically includes system manufacturer, model name, serial number, BIOS
version, asset tag as well as a lot of other details of varying level of
interest and reliability depending on the manufacturer. This will often
include usage status for the CPU sockets, expansion slots (e.g. AGP, PCI,
ISA) and memory module slots, and the list of I/O ports (e.g. serial,
parallel, USB).

%package bin
Summary: bin components for the dmidecode package.
Group: Binaries
Requires: dmidecode-license
Requires: dmidecode-man

%description bin
bin components for the dmidecode package.


%package doc
Summary: doc components for the dmidecode package.
Group: Documentation
Requires: dmidecode-man

%description doc
doc components for the dmidecode package.


%package license
Summary: license components for the dmidecode package.
Group: Default

%description license
license components for the dmidecode package.


%package man
Summary: man components for the dmidecode package.
Group: Default

%description man
man components for the dmidecode package.


%prep
%setup -q -n dmidecode-3.2
%patch1 -p1
%patch2 -p1

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1537206743
make  %{?_smp_mflags}

%install
export SOURCE_DATE_EPOCH=1537206743
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/doc/dmidecode
cp LICENSE %{buildroot}/usr/share/doc/dmidecode/LICENSE
%make_install

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/biosdecode
/usr/bin/dmidecode
/usr/bin/ownership
/usr/bin/vpddecode

%files doc
%defattr(0644,root,root,0755)
%doc /usr/share/doc/dmidecode/*

%files license
%defattr(-,root,root,-)
/usr/share/doc/dmidecode/LICENSE

%files man
%defattr(-,root,root,-)
/usr/share/man/man8/biosdecode.8
/usr/share/man/man8/dmidecode.8
/usr/share/man/man8/ownership.8
/usr/share/man/man8/vpddecode.8
